### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by frankhommers** [krisc-informatica/arduino-smart-bike-trainer#2]
Hi there. I just came across your repo. I'd like to be able to do this as well.

Is this anywhere near completion? 
Do I need a circuitboard for this? 
Are there any schematics?
Can I help? :-)

**Comment by krisc-informatica** [comment]
Hello Frank,

thanks for your interest. The latest code (from Jan. 24rd) contains all the code except the actual calculation of the brake pwm that is needed. I have to include that still.

In the discussions part of this project (https://github.com/krisc-informatica/arduino-smart-bike-trainer/discussions/1) is a link to a schema for a PCB. That is also WIP still. I'm thinking of adding a connector to connect a small LCD screen (1602A or so) and some general buttons that could be used in code for different reasons.

**Comment by frankhommers** [comment]
Ah did not see the discussion. Thx.
